---
title: "UK Companies House multiple companies"
author: "Sara Hassani"
date: "2024-08-24"
output: html_document
---

# Getting Company information using UK Companies House REST API

```{r}
library(jsonlite)
library(httr)
library(googlesheets4)
library(shiny)

api_key = ""
sic = read.csv("SIC07_CH_condensed_list_en.csv") # can download csv file from UK companies House

```

## Core Functions

```{r}

# Function to run search using the company name

company_name_search = function(api_key, company){
  
# connect to API
  headers = c(
  api_key = api_key,
  'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  
# standardize company name
  company_name = gsub("[^A-Za-z0-9 ]", "", tolower(company))
  company_name = gsub(" ", "+", company_name)
  
# extract search pages
  url = paste0("https://api.company-information.service.gov.uk/search?q=", company_name)
  res = VERB("GET", url = url, add_headers(headers))
  response_list = fromJSON(content(res, 'text'), flatten = TRUE)
  response_df = response_list$items
  
# keep only companies
  response_df = subset(response_df, response_df$kind == "searchresults#company")
  
# standardize company names from searches
  response_df$title_standard = gsub("[[:punct:]]", "", response_df$title)
  company = gsub("\\+", " ", toupper(company_name))

  index = which(response_df$title == company)
  name_number = data.frame(NAME = response_df$title[index], NUMBER = response_df$company_number[index], STATUS = response_df$company_status[index])
  ifelse(
    length(index) > 0, 
    return(name_number), 
    return("no match")
    )
}

# Function to obtain the company number from the company name

company_name_to_number = function(api_key, company_name){
  
  # standardizing the company name
  company = gsub("[^A-Za-z0-9 ]", "", tolower(company_name))
  # vector to store possible variations of the name
  options <- company

  # Check for the presence of abbreviations for company type to look for possible variation of the company name
    # Limited Liability Company
  if (grepl("\\bllc\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bllc\\b", "limited liability company", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bllc\\b", "", company, ignore.case = TRUE))
  } else if (grepl("\\blimited liability company\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\blimited liability company\\b", "llc", company, ignore.case = TRUE))
    options <- c(options, gsub("\\blimited liability company\\b", "", company, ignore.case = TRUE))
  }
    # Limited Partnership
  if (grepl("\\bltd\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bltd\\b", "limited", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bltd\\b", "", company, ignore.case = TRUE))
    } else if (grepl("\\blimited\\b$", company, ignore.case = TRUE)) {
      options <- c(options, gsub("\\blimited\\b", "ltd", company, ignore.case = TRUE))
      options <- c(options, gsub("\\blimited\\b", "", company, ignore.case = TRUE))
    }
    # Corporation
  if (grepl("\\bcorp\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bcorp\\b", "corporation", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bcorp\\b", "", company, ignore.case = TRUE))
  } else if (grepl("\\bcorporation\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bcorporation\\b", "corp", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bcorporation\\b", "", company, ignore.case = TRUE))
  }
    # Public Limited Company
  if (grepl("\\bplc\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bplc\\b", "public limited company", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bplc\\b", "", company, ignore.case = TRUE))
  } else if (grepl("\\bpublic limited company\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bpublic limited company\\b", "plc", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bpublic limited company\\b", "", company, ignore.case = TRUE))
  }
    # Limited Liability Partnership
  if (grepl("\\bllp\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bllp\\b", "limited liability partnership", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bllp\\b", "", company, ignore.case = TRUE))
  } else if (grepl("\\blimited liability partnership\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\blimited liability partnership\\b", "llp", company, ignore.case = TRUE))
    options <- c(options, gsub("\\blimited liability partnership\\b", "", company, ignore.case = TRUE))
  }
    # Limited Partnership
  if (grepl("\\blp\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\blp\\b", "limited partnership", company, ignore.case = TRUE))
    options <- c(options, gsub("\\blp\\b", "", company, ignore.case = TRUE))
  } else if (grepl("\\blimited partnership\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\blimited partnership\\b", "lp", company, ignore.case = TRUE))
    options <- c(options, gsub("\\blimited partnership\\b", "", company, ignore.case = TRUE))
  }
  # Industrial and provident Society
  if (grepl("\\bips\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bips\\b", "Industrial and Provident Society", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bips\\b", "", company, ignore.case = TRUE))
  } else if (grepl("\\bIndustrial and Provident Society\\b$", company, ignore.case = TRUE)) {
    options <- c(options, gsub("\\bIndustrial and Provident Society\\b", "ips", company, ignore.case = TRUE))
    options <- c(options, gsub("\\bIndustrial and Provident Society\\b", "", company, ignore.case = TRUE))
  }

  # Ensure unique options
  options <- unique(options)

  # Setting up for number search
  x = length(options)
  results = data.frame(search = options, company_name = rep(NA, x), 
                       company_number = rep(NA, x), 
                       status = rep(NA, x ))

  # Search for matches across variations
  api_key = api_key
  
  for(mu in 1:x){
    company = options[mu]
    results[mu,2:4] = company_name_search(api_key, company)
  }
    # only keep positive matches
  positive = subset(results, company_number != "no match")
  return(positive)
  
}

# Function to extract general company information from the company number

general_info = function(api_key, company_number, sic){
  
    headers = c(
     api_key = api_key,
    'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  url = paste0("https://api.company-information.service.gov.uk/company/", company_number)
  res <- VERB("GET", url = url, add_headers(headers))
  response_list <- fromJSON(content(res, 'text'), flatten = TRUE)
  
  if ((is.list(response_list) && length(response_list) == 0) || 
      (is.data.frame(response_list) && nrow(response_list) == 0)) {
    response_df = data.frame(return = "N/A")
    return(response_df)
  }else{
  
  # Office Address
  if("registered_office_address" %in% names(response_list)){
    office = as.data.frame(t(as.data.frame(response_list$registered_office_address)))
    rows = 1:nrow(office)
    entries = office[rows, 1]
    registered_office = paste(entries, collapse = ", ")
  }
  
  # Industry
  if("sic_codes" %in% names(response_list)){
    x = which(response_list$sic_codes == sic$SIC.Code)
    
    if(is.integer(x) && length(x) == 0){
      industry = paste0(response_list$sic_codes, "- no match on concentrated codes list")
    }else{
      industry = sic$Description[x]
    }
  }else{
      industry = "N/A"
  }
  
  # Liquidation
  if("has_been_liquidated" %in% names(response_list)){
    liquidated = ifelse(response_list$has_been_liquidated == FALSE, "N/A", "Yes")
  }else{
      liquidated = "N/A"
  }

  # Charges
  if("has_charges" %in% names(response_list)){
    charges = ifelse(response_list$has_charges == FALSE, "N/A", "Yes")
  }else{
      charges = "N/A"
  }
  
  # Insolvency
  if("has_insolvency_history" %in% names(response_list)){
    insolvency = ifelse(response_list$has_insolvency_history == FALSE, "N/A", "Yes")
  }else{
      insolvency = "N/A"
  }
  
  # Jurisdiction
  if("jurisdiction" %in% names(response_list)){
    jurisdiction = response_list$jurisdiction
  }else{
      jurisdiction = "N/A"
  }
 
  # Previous names
    if("previous_company_names" %in% names(response_list)){
    
    # Previous Names
    names = response_list$previous_company_names[, c(3,2,1)]
    rows = 1:nrow(names)
    entries = names[rows, 1] 
    previous_names = paste(entries, collapse = ", ")
    
    # Current Name
    name_dates = as.vector(unlist(names[, c(2,3)]))
    name_dates = as.Date(name_dates)
    current_name_date = max(name_dates)
    
    }else{
     previous_names = "N/A"
     current_name_date = response_list$date_of_creation
  }
  
  # Dissolution date
  if("date_of_cessation" %in% names(response_list)){
    dissolution_date =  response_list$date_of_cessation
    }else{
     dissolution_date = "N/A"
    }
  
  # Output
  response_df = data.frame(
    company_name = response_list$company_name,
    company_number = response_list$company_number,
    incorporation_date = response_list$date_of_creation,
    status = response_list$company_status,
    dissolution_date = dissolution_date,
    industry = industry,
    previous_names = previous_names,
    date_current_name = current_name_date,
    jurisdiction = jurisdiction,
    registered_office = registered_office,
    liquidated = liquidated,
    charges = charges,
    insolvency = insolvency
  )
  
  general = as.data.frame(t(response_df))
  general <- cbind(RowName = rownames(general), general)
  rownames(general) <- NULL
  colnames(general) = NULL
  
  return(general)
  }
}

# Function to extract company officer information from the company number

officer_info = function(api_key, company_number){
  
 headers = c(
     api_key = api_key,
    'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  url = paste0("https://api.company-information.service.gov.uk/company/", company_number, "/officers")
  res <- VERB("GET", url = url, add_headers(headers))
  response_list <- fromJSON(content(res, 'text'), flatten = TRUE)
  response_df = response_list$items
  
  if ((is.list(response_df) && length(response_df) == 0) || 
      (is.data.frame(response_df) && nrow(response_df) == 0)) {
    response_df = data.frame(return = "N/A")
    return(response_df)
  }else{
  
  if("resigned_on" %in% names(response_list)){
    resigned_on = response_df$resigned_on
  }else{
    resigned_on = "N/A"
  }
  
  directors = data.frame(
    name = response_df$name,
    nationality = response_df$nationality,
    country_of_residence = response_df$country_of_residence,
    role = response_df$officer_role,
    date_appointed = response_df$appointed_on,
    date_resignation = resigned_on,
    original_occupation = response_df$occupation
  ) 
  
  # Registered Address
  address = data.frame(
    response_df$address.address_line_1,
    response_df$address.locality,
    response_df$address.postal_code
  )
  combined_rows = apply(address, 1, function(x) paste(x, collapse = ", ")) # need to add way to remove NA before merging
  
  directors$registered_address = combined_rows
  
  # Date of Birth
  dob = data.frame(
    response_df$date_of_birth.month,
    response_df$date_of_birth.year
  )
  combined_rows = apply(dob, 1, function(x) paste(x, collapse = "-")) # need to add way to remove NA before merging
  
  directors$dob = combined_rows
  
  directors[is.na(directors)] <- ""

  return(directors)
  }
}

# Function to extract Person with Significant Control information from the company number

psc_info = function(api_key, company_number){
  
  headers = c(
     api_key = api_key,
    'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  url = paste0("https://api.company-information.service.gov.uk/company/", company_number, "/persons-with-significant-control")
  res <- VERB("GET", url = url, add_headers(headers))
  response_list <- fromJSON(content(res, 'text'), flatten = TRUE)
  response_df = response_list$items
  
  # Check if response_df is an empty list or empty dataframe
  if ((is.list(response_df) && length(response_df) == 0) || 
      (is.data.frame(response_df) && nrow(response_df) == 0)) {
    response_df = data.frame(return = "N/A")
    return(response_df)
    stop()
  }else{
  
  # DOB
  if("date_of_birth.month" %in% names(response_df)){
    if("date_of_birth.year" %in% names(response_df)){
  dob = data.frame(
    response_df$date_of_birth.month,
    response_df$date_of_birth.year
  )
  combined_rows = apply(dob, 1, function(x) paste(x, collapse = "-")) # need to add way to remove NA before merging
  dob = data.frame(date_of_birth = combined_rows) 
    }else{dob = rep("N/A", nrow(response_df))}
  }else{dob = rep("N/A", nrow(response_df))}
    
  # Control
  if(is.list(response_df$natures_of_control)){
    control <- sapply(response_df$natures_of_control, function(x) paste(x, collapse = ", '"))
  }
  
  # Date of cessation
  if("ceased_on" %in% names(response_df)){
    date_ceased = response_df$ceased_on
  }else{
    date_ceased = rep("N/A", nrow(response_df))
  }
    
  # Nationality
  if("nationality" %in% names(response_df)){
    nationality = response_df$nationality
  }else{
    nationality = rep("N/A", nrow(response_df))
  }
    
  # Country of residence
  if("country_of_residence" %in% names(response_df)){
    country_of_residence = response_df$country_of_residence
  }else{
    country_of_residence = rep("N/A", nrow(response_df))
  }
    
  # Country of Address
    # Country of residence
  if("address.country" %in% names(response_df)){
    country_of_address = response_df$address.country
  }else{
    country_of_address = rep("N/A", nrow(response_df))
  }
     
  # PSC
  psc = data.frame(
    name = response_df$name,
    control = control,
    date_notified = response_df$notified_on,
    ceased = response_df$ceased,
    date_ceased = date_ceased,
    dob = dob,
    nationality = nationality,
    country_of_residence = country_of_residence,
    country_of_address = country_of_address
  )
  
  return(psc)
  }
}

# Function to extract the list of available documents from the company number

documents_available = function(api_key, company_number){
  
  headers = c(
     api_key = api_key,
    'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  url = paste0("https://api.company-information.service.gov.uk/company/", company_number, "/filing-history")
  res <- VERB("GET", url = url, add_headers(headers))
  response_list <- fromJSON(content(res, 'text'), flatten = TRUE)
  
  response = response_list$items
  
  documents = data.frame(
    description = response$description,
    category = response$category,
    date = response$date,
    pages = response$pages,
    id = response$transaction_id
  )
  
  return(documents)
}

# Function to extract charges information from the company number

charges = function(api_key, company_number){
  
  headers = c(
     api_key = api_key,
    'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  url = paste0("https://api.company-information.service.gov.uk/company/", company_number, "/charges")
  res <- VERB("GET", url = url, add_headers(headers))
  response_list <- fromJSON(content(res, 'text'), flatten = TRUE)
  
  response_df = response_list$items

  # Entitled Persons
  entitled_persons <- sapply(response_df$persons_entitled, function(df) {
    apply(df, 1, paste, collapse = ", ") %>% 
    paste(collapse = ", ")
    }
  )

  charges = data.frame(
    charge_type = response_df$classification.description,
    entitled_persons = entitled_persons,
    description = response_df$particulars.description,
    created = response_df$created_on,
    status = response_df$status,
    satisfied = response_df$satisfied_on
  )

  return(charges)
}

# Function to extract insolvency information from the company number

insolvency = function(api_key, company_number){
  headers = c(
     api_key = api_key,
    'Authorization' = 'Basic YTdkOWMzYjYtMjY3ZC00YmY1LWIwNzAtMmM3ODA4MzlkNTI5Og=='
  )
  url = paste0("https://api.company-information.service.gov.uk/company/", company_number, "/insolvency")
  res <- VERB("GET", url = url, add_headers(headers))
  response_list <- fromJSON(content(res, 'text'), flatten = TRUE)
  
  response_df = response_list$cases

  x = nrow(response_df)
  
  type = rep(NA, x)
  practitioners = rep(NA, x)
  dates = as.data.frame(matrix(NA, ncol = 2, nrow = x))

  
  for(i in 1:x){
    # Type of case
    if("type" %in% names(response_df)){
       type[i] = response_df$type[i]
       }else{
         type[i] = "N/A"
       }
    
    # Practitioners
    if("practitioners" %in% names(response_df)){
      p = as.data.frame(response_df$practitioners[1])
      practitioners[i] = paste(p$name, collapse = ", ")
    }else{
      practitioners[i] = "N/A"
    }
    
    # Dates of case
    if("dates" %in% names(response_df)){
      d = as.data.frame(response_df$dates[1])
      t = t(d[,2, drop=FALSE])
      dates[i,] = as.data.frame(t)
      colnames(dates) = d[,1]
    }else{
      dates[i,] = rep("N/A", 2)
    }
  }
  
  insolvency = data.frame(
    type, 
    practitioners
  )
    
  insolvency = cbind(insolvency, dates)
    
  return(insolvency)
}

# Function to create data frame with company information, including officer and psc names

info_list = function(api_key, positive, sic){  
  
  info_list = data.frame(matrix(ncol = 15, nrow = 0))
  colnames(info_list) = c("company_name", "company_number", "incorporation date", 
                        "status", "industry", "dissolution_date", "jurisdiction", 
                        "registered_office", "previous_names", "date_of_current_name", 
                        "liquidated", "charges", "insolvency", "officers", "psc")
  
  x = nrow(positive)
  api_key = api_key
  sic = sic
  
  # create list with information on each of the matches
  for(rho in 1:x){
  
    company_number = positive$company_number[rho]
  
    # Extract all the relevant information
    company_overview = general_info(api_key, company_number, sic)
    officers = officer_info(api_key, company_number)
    psc = psc_info(api_key, company_number)
  
    # Enrich company overview
    a = paste(officers$name, collapse = "; ")
    b = paste(psc$Name, collapse = "; ")
  
    company_overview = as.data.frame(t(company_overview))
    colnames(company_overview) = company_overview[1,]
    company_overview = company_overview[-1,]
  
    company_overview$officers = a
    company_overview$psc = b
  
    info_list = rbind(info_list, company_overview)
    
  }
  
  return(info_list)
  
}

```

# Extracting Company Information using UK Comapnies House API - MULTIPLE COMPANY SEARCH

USER INPUT :

```{r}

project = "chips perfume"
companies = "company 1, company 2, company 3, company 4, ..." # does not work if the company's name has special characteristics

```

CODE OUTPUT :

```{r}

# split the company names
company_vector <- unlist(strsplit(companies, ", "))

l = length(company_vector)
project_search = data.frame(matrix(ncol = 16, nrow = 0))
colnames(project_search) = c("company_name", "company_number", "incorporation date", 
                      "status", "industry", "dissolution_date", "jurisdiction", 
                      "registered_office", "previous_names", "date_of_current_name", 
                      "liquidated", "charges", "insolvency", "officers", "psc", "extracted")

for(z in 1:l){
  
  company_name = company_vector[z]
  
  # Getting matches for the company number 
  positive = company_name_to_number(api_key, company_name)
  
  x = nrow(positive)

  if (x == 0) { next }
  
  if (x > 1) {

    information = info_list(api_key, positive, sic)
    information$extracted = rep("N", x)
    project_search = rbind(project_search, information)
    
    next
    
  } # Skipping at this stage, if all works out, can come back to find a way to infuse user input about specific company number 
  
 
  if (x == 1) {

# Extract company information for the project overview
   information = info_list(api_key, positive, sic)
   information$extracted = rep("N", x)
   project_search = rbind(project_search, information)
    
# Extract individual sheet per company match
    company_number = positive$company_number[1]

    # Extract company information 
    company_overview = general_info(api_key, company_number, sic)

    # Extract officers' information
    officers = officer_info(api_key, company_number)

    # Extract PSC information
    psc = psc_info(api_key, company_number)

    # Extract list of documents
    documents = documents_available(api_key, company_number)

    # Extract charges
    gamma = company_overview[9, 2]
    gamma = unlist(as.vector(gamma))
    
    if(gamma == "Yes"){
      charges = charges(api_key, company_number)
      }else{
        charges = data.frame(charges = "N/A")
      }
    
    # Extract insolvency
    gamma = company_overview[13, 2]
    gamma = unlist(as.vector(gamma))
    
    if(gamma == "Yes"){
      insolvency = insolvency(api_key, company_number)
      }else{
        insolvency = data.frame(insolvency = "N/A")
      }

    # Create Excel Sheet for the company
    a = positive$company_number[1]
    b = toupper(positive$company_name[1])
    sheet_title = paste0(a, "_", b)
    
    # Data
    final = list(Company_Overview = company_overview, 
                 Officers = officers, 
                 PSC = psc, 
                 Charges = charges, 
                 Insolvency = insolvency,
                 Documents = documents)

    # unfortunately there are no options to create a Google sheet directly into a specific folder
    gs4_create(name = sheet_title, sheets = final)

  }
}

# Extract the information list
b = toupper(project)
gs4_create(name = b, sheets = project_search)

```
